Shopping/Models/CityViewModel.cs
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;

namespace Shopping.Models
{
    public class CityViewModel
    {
        // propiedad PK
        public int Id { get; set; }

        // Nombre modificado para el usuario

        [Display(Name = "Ciudades")]

        // Limitacion de los Caracteres 

        [MaxLength(50, ErrorMessage = "El {0} no puedes superar los {1} caracteres")]

        // Obligacion de llenar el campo para el usuario

        [Required(ErrorMessage = "El {0} es obligatorio")]

        public string Name { get; set; }
        [JsonIgnore]
        public int StateId { get; set; }
    }
}

Shopping/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Shooping.Helpers;
using Shopping.Data;
using Shopping.Data.Entities;
using Shopping.Models;
using System.Diagnostics.Metrics;
using Vereyon.Web;
using static Shooping.Helpers.ModalHelper;

namespace Shopping.Controllers
{
    [Authorize(Roles = "Admin")]
    // El controlador es una clase que herada de una clase mas grande llamada 
    // Controller, esta clase es propia del framework Entitys
    public class CountriesController : Controller
    {
        // Se crea un atributo privado llamado _context, el cual tiene toda la
        // información del contexto de datos
        private readonly DataContex _context;
        private readonly IFlashMessage _flashMessage;

        // Se inyecta información a traves del parametro "context"
        // por eso es de tipo DataContex, el caul trae la conexión.
        public CountriesController(DataContex context, IFlashMessage flashMessage)
        {
            _context = context;
            _flashMessage = flashMessage;
        }

        // GET: Countries a traves del metodo Index siempre y cuando cumpla el requisito de la interfaz
        public async Task<IActionResult> Index()
        {
            return View(await _context.countries
                .Include(c => c.States)
                .ThenInclude(s => s.Cities)
                .ToListAsync());
        }


        // GET: Countries/Details/5, el "int? id" se refiere a que puede o no recibir un id
        public async Task<IActionResult> Details(int? id)
        {
            // Aqui le dice que si el id es nulo o no hay un registro en la entidad countries
            // mandelo a una pagina personalizada llamada "NotFound"
            if (id == null || _context.countries == null)
            {
                return NotFound();
            }

            /* Manda una peticion para obtener el country que tenga el mismo id que el 
             digitado, en caso de que no exista lo envia a "NotFound", si existe le 
             muetsra el pais*/
            var country = await _context.countries.Include(c => c.States).ThenInclude(s=>s.Cities)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (country == null)
            {
                return NotFound();
            }

            return View(country);
        }


        public async Task<IActionResult> DeleteCity(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            City city = await _context.cities
                .Include(c => c.State)
                .FirstOrDefaultAsync(c => c.Id == id);
            if (city == null)
            {
                return NotFound();
            }

            try
            {
                _context.cities.Remove(city);
                await _context.SaveChangesAsync();
            }
            catch
            {
                _flashMessage.Danger("No se puede borrar la ciudad porque tiene registros relacionados.");
            }

            _flashMessage.Info("Registro borrado.");
            return RedirectToAction(nameof(DetailsState), new { Id = city.State.Id });
        }

        [NoDirectAccess]
        public async Task<IActionResult> EditCity(int id)
        {
            City city = await _context.cities
                .Include(c => c.State)
                .FirstOrDefaultAsync(c => c.Id == id);
            if (city == null)
            {
                return NotFound();
            }

            CityViewModel model = new()
            {
                StateId = city.State.Id,
                Id = city.Id,
                Name = city.Name,
            };

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditCity(int id, CityViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    City city = new()
                    {
                        Id = model.Id,
                        Name = model.Name,
                    };
                    _context.Update(city);
                    await _context.SaveChangesAsync();
                    State state = await _context.states
                        .Include(s => s.Cities)
                        .FirstOrDefaultAsync(c => c.Id == model.StateId);
                    _flashMessage.Confirmation("Registro actualizado.");
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllCities", state) });
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        ModelState.AddModelError(string.Empty, "Ya existe una ciuad con el mismo nombre en este departamento/estado.");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    ModelState.AddModelError(string.Empty, exception.Message);
                }
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "EditCity", model) });
        }

        // GET: Countries/Details/5, el "int? id" se refiere a que puede o no recibir un id
        [NoDirectAccess]
        public async Task<IActionResult> DetailsState(int id)
        {
          

            State state = await _context.states
                .Include(s => s.Country)
                .Include(s => s.Cities)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (state == null)
            {
                return NotFound();
            }

            return View(state);
        }

        // GET: Countries/Create se trae la pagina para mostrar al usuario



        [NoDirectAccess]
        public async Task<IActionResult> EditState(int id)
        {

            State states = await _context.states.Include(s=>s.Country).FirstOrDefaultAsync(s => s.Id==id);

            StateViewModel model = new()
            {

                CountryId = states.Country.Id,
                Id = states.Id,
                Name = states.Name

            };

            return View(model);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditState(int id, StateViewModel model)
        {
            if (id != model.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    State state = await _context.states.FindAsync(model.Id);
                    state.Name = model.Name;
                    _context.Update(state);
                    Country country = await _context.countries
                        .Include(c => c.States)
                        .ThenInclude(s => s.Cities)
                        .FirstOrDefaultAsync(c => c.Id == model.CountryId);
                    await _context.SaveChangesAsync();
                    return Json(new { isValid = true, html = ModalHelper.RenderRazorViewToString(this, "_ViewAllStates", country) });
                }
                catch (DbUpdateException dbUpdateException)
                {
                    if (dbUpdateException.InnerException.Message.Contains("duplicate"))
                    {
                        _flashMessage.Danger("Ya existe un Departamento / Estado con el mismo nombre.");
                    }
                    else
                    {
                        _flashMessage.Danger(dbUpdateException.InnerException.Message);
                    }
                }
                catch (Exception exception)
                {
                    _flashMessage.Danger(exception.Message);
                }
            }

            return Json(new { isValid = false, html = ModalHelper.RenderRazorViewToString(this, "EditState", model) });
        }



        [NoDirectAccess]

        [HttpGet]
        public async Task<IActionResult> AddState(int id) 
        { 


            Country country = await _context.countries.FindAsync(id);
            if (country == null)
            {
                return NotFound();
            }

            StateViewModel model = new()
            {
                CountryId = country.Id,
            };
        
            return View(model);
        }

        // POST: Countries/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.

        [HttpPost]
        [ValidateAntiForgeryToken]
        // Debido a que este es un "Post" osea que se envian información se necesitan
        // parametros que determinen la información en este caso es country
        public async Task<IActionResult> AddState(StateViewModel model)
        {
            // si el modelo es valido osea si los campos estan llenos y no rompe ninguna
            // regla añade el pais y envia el cambio, redireccionandolo a Index

            if (ModelState.IsValid)
            {

                try
                {
                    // Se crea el objeto State que se añadira mas adelante en el Post
                    State state = new()
                    {
                        Cities = new List<City>(),
                        Country = await _context.countries.FindAsync(model.CountryId),
                        Name = model.Name,

                    };

Shopping/Views/Countries/AddCity.cshtml
@model Shopping.Models.CityViewModel

@{
    ViewData["Title"] = "AddState";
}

<h1>Crear</h1>

<h4>Ciudad</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="AddCity">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="StateId" />

            <partial name="_City" /> 


            <div class="form-group mt-2">
                <input type="submit" value="Crear" class="btn btn-outline-primary" />
                <a asp-action="DetailsState" asp-route-id="@Model.StateId" class="btn btn-outline-success">Volver a la lista</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Shopping/Views/Countries/AddOrEdit.cshtml
@model Shopping.Data.Entities.Country

@{
    ViewData["Title"] = "País";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddOrEdit" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <span class="required">*</span>
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control smfont" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Shopping/Views/Countries/AddState.cshtml
@model Shopping.Models.StateViewModel

@{
    ViewData["Title"] = "Estado / Departamento";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="AddState" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="CountryId" />
            <partial name="_State" />
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Shopping/Views/Countries/DeleteCity.cshtml
@model Shopping.Data.Entities.City

@{
    ViewData["Title"] = "Delete";
}

<h1>Borrar</h1>

<h3>¿Esta seeguro de querer borrar?</h3>
<div>
    <partial name="_CityDetails" />
    <form asp-action="DeleteCity">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Borrar" class="btn btn-outline-danger" />
        <a asp-action="DetailsState" asp-route-id="@Model?.State.Id" class="btn btn-outline-success">Regresar</a>
    </form>
</div>

Shopping/Views/Countries/DeleteState.cshtml
@model Shopping.Data.Entities.State

@{
    ViewData["Title"] = "Eliminar";
}

<h1>Eliminar</h1>

<h3>¿Esta seguro de eliminar esto?</h3>
<div>

    <partial name="_DeleteState" />


    <form asp-action="DeleteState">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Eliminar" class="btn btn-outline-danger" /> |
        <a asp-action="Index" class="btn btn-outline-success">Volver a la lista</a>
    </form>
</div>

Shopping/Views/Countries/DetailsState.cshtml
@model Shopping.Data.Entities.State

@{
    ViewData["Title"] = "Details";
}

<flash dismissable="true" />

<h1>Detalles</h1>

<div>
    <partial name="_StateDetails" />
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model?.Country.Id" class="btn btn-outline-success"><i class="fa-solid fa-arrow-rotate-left"></i> Regresar</a>
</div>
<hr />

<!-- Content Wrapper. Contains page content -->
<div class="container-fluid">
    <div class="card mt-2">
        <div class="card-header text-danger">
            <i class="fa fa-object-group"></i>  <strong>Ciudades</strong>
        </div>
        <div class="card-body">
            <div id="view-all">
                @await Html.PartialAsync("_ViewAllCities", Model)
            </div>
        </div>
    </div>
</div>


<partial name="_AddOrEditDialog" />
<partial name="_DeleteDialog" />

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }

    <script src="~/js/showmodal.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#StatesTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json"
                },
                "aLengthMenu": [
                    [25, 50, 100, 200, -1],
                    [25, 50, 100, 200, "Todos"]
                ]
            });
        });
    </script>

    <script>
        sc_deleteDialog.openModal('deleteItem', true, 'btnYesDelete', '/Countries/DeleteCity/', false);
    </script>
}

Shopping/Views/Countries/EditState.cshtml
@model Shopping.Models.StateViewModel

@{
    ViewData["Title"] = "Estado / Departamento";
    Layout = null;
}

<flash dismissable="true" />

<div class="container smfont">
    <form asp-action="EditState" autocomplete="off" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
        <div class="box-body">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="CountryId" />
            <partial name="_State" />
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-sm btn-primary" data-bs-dismiss="modal"><i class="fa fa-ban"></i> Cancelar</button>
            <button type="submit" class="btn btn-sm btn-success"><i class="fa fa-save"></i> Guardar</button>
        </div>
    </form>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Shopping/Views/Countries/_City.cshtml
@model Shopping.Models.CityViewModel

<div class="form-group">
    <span class="required">*</span>
    <label asp-for="Name" class="control-label"></label>
    <input asp-for="Name" class="form-control" />
    <span asp-validation-for="Name" class="text-danger"></span>
</div>

Shopping/Views/Countries/_Countrydetails.cshtml
@model Shopping.Data.Entities.Country

<h4>Pais</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>

    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.StatesNumber)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.StatesNumber)
    </dd>

</dl>

Shopping/Views/Countries/_DeleteState.cshtml
@model Shopping.Data.Entities.State

<h4>Departamento/Estado</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>

    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.CitiesNumber)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.CitiesNumber)
    </dd>

</dl>

Shopping/Views/Countries/_StateDetails.cshtml
@model Shopping.Data.Entities.State

<h4>Departamento/Estado</h4>
<hr />
<dl class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>

    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.CitiesNumber)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.CitiesNumber)
    </dd>

</dl>

Shopping/Views/Countries/_ViewAll.cshtml
@model IEnumerable<Shopping.Data.Entities.Country>

<flash dismissable="true" />

<table class="table table-striped table-responsive-md table-bordered smfont" id="CountriesTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StatesNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CitiesNumber)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddOrEdit", "Countries", new { id = 0 }, Context.Request.Scheme)' , 'Nuevo País')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i> País</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <a asp-action="Details" asp-controller="Countries" asp-route-Id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StatesNumber)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CitiesNumber)
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("AddOrEdit", "Countries", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar País')" class="btn btn-sm btn-warning"><i class="fa fa-pencil-alt"></i> </a>
                    <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
                </td>
            </tr>
        }
    </tbody>
</table>

Shopping/Views/Countries/_ViewAllCities.cshtml
@model Shopping.Data.Entities.State

<flash dismissable="true" />

<table class="table table-striped table-responsive-md table-bordered smfont" id="StatesTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cities.FirstOrDefault().Name)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddCity", "Countries", new { id = Model.Id }, Context.Request.Scheme)' , 'Nueva Ciudad')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i> Ciudad</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Cities)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => item.Name)
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("EditCity", "Countries", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar Ciudad')" class="btn btn-sm btn-warning"><i class="fa fa-pencil-alt"></i> </a>
                    <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
                </td>
            </tr>
        }
    </tbody>
</table>

Shopping/Views/Countries/_ViewAllStates.cshtml
@model Shopping.Data.Entities.Country

<flash dismissable="true" />

<table class="table table-striped table-responsive-md table-bordered smfont" id="StatesTable">
    <colgroup>
        <col span="1" />
        <col span="1" />
    </colgroup>
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.States.FirstOrDefault().Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.States.FirstOrDefault().CitiesNumber)
            </th>
            <th>
                <a onclick="showInPopup('@Url.Action("AddState", "Countries", new { id = Model?.Id }, Context.Request.Scheme)' , 'Nuevo Estado / Departamento')" class="btn btn-sm btn-primary text-white"><i class="fa fa-plus-circle"></i> Estado / Departamento</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model?.States)
        {
            <tr>
                <td>
                    <a asp-action="DetailsState" asp-controller="Countries" asp-route-Id="@item.Id">@Html.DisplayFor(modelItem => item.Name)</a>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CitiesNumber)
                </td>
                <td>
                    <a onclick="showInPopup('@Url.Action("EditState", "Countries", new { id = item.Id }, Context.Request.Scheme)' , 'Actualizar Estado / Departamento')" class="btn btn-sm btn-warning"><i class="fa fa-pencil-alt"></i> </a>
                    <button data-id="@item.Id" class="btn btn-sm btn-danger deleteItem" data-bs-toggle="modal" data-bs-target="#deleteDialog"><i class="fa fa-trash"></i></button>
                </td>
            </tr>
        }
    </tbody>
</table>